REST APIの実装
pfp-shunsuke/assignment pull request #2
Opened 2021-05-11 10:09 UTC by pfp-shunsuke

芸人さんの情報を操作するREST APIを開発。

2021-05-12 00:35 UTC, primalcode requested changes

2021-05-12 00:35 UTC, primalcode commented on my-app/src/main/java/com/assignment/controller/ComediansController.java
> +    final ComedianService comedianService;
privateもつけましょう．

2021-05-12 00:35 UTC, primalcode commented on my-app/src/main/java/com/assignment/controller/ComediansController.java
> +    ResponseEntity<Object> putById(@RequestBody Comedian comedian) {
JavaDocコメントを書く癖をつけましょう．

2021-05-12 00:35 UTC, primalcode commented on my-app/src/main/java/com/assignment/controller/ComediansController.java
> +     */
ここはJavaDocコメントあっていいですね！
プラスで@returnも書きましょう．

2021-05-12 00:35 UTC, primalcode commented on my-app/src/main/java/com/assignment/domain/Comedian.java
> +@Data
@Valueについてもみてみてください．

2021-05-12 00:35 UTC, primalcode commented on my-app/src/test/requests/delete-requests.http
> +###PK指定削除
deleteに限らず，単体テストはJUnitとSpockを使いますので，是非チャレンジしてみてください！

2021-05-12 07:22 UTC, pfp-shunsuke commented on my-app/src/main/java/com/assignment/domain/Comedian.java
> +@Data
valueを使うとimmutableになるんですね。
今回の使い方でいうと、valueのほうが適していそうです。

2021-05-18 01:49 UTC, pfp-shunsuke commented on my-app/src/test/requests/delete-requests.http
> +###PK指定削除
コントローラーの単体テストにSpockを使ってみました。
いろいろ調べながらやっていたので、
正常系までは一旦作ることはできたのですが、異常系は時間が足りませんでした。

2021-05-25 00:05 UTC, primalcode approved these changes
LGTM.

2021-06-05 03:48 UTC, merged